travis:
  secure:
    BINSTAR_TOKEN: ABwhMfx6F8CyNWOks2RmM/1crng5b/Xv0CEyyAxyEnq6KmL66qITC0aCtg/KEaT9BO/E8nB/JkUh29g+BKFwShMDPS8umBklL+/033k6ALEuPDIgvZe931qIKwfj15d7OeE03yEl05TLJsbl0avTEC6pO6gqIJKMap2YyeaD8vh+Y5g6TDjx9kuCjcr09MVmLO9Wx1MUHfZU7Um/LMlSiE/UWClcRRtmcXhxbloOoawMwzxfvTkCwJjx5I/IaeJQVyU+oVslsA+bHPZsF7EeKxwtuDtdPV4/3Ouh4sUWuRDioMDM6JP3prZyPXA6t02Ik+TIGZ2P3TXMQG102R8ZUlCCV7Quh3yvTmXZamMOfITQ6toX6ehkGbI4Se8J3l0Aimy9vn6t2HqCiUQ/hLSltXApbPFxNnlaG1aOiVjOWJpHavwWaLETXad1XG5LaasW5nzndVdMyMLS9NSPxTRIsOkH+uLqeSQw4xvI8BMiNQDHX03/DE9afPQF0BE7Bg8adO/X7xxmK6W6AMHVB/uD2XzkfulBYWUXcW5yTnK3EetAJXHm5imb0tzmqllFrxUNpQdbb89NRWWT+449KQasnndfUz3WRsfNezEnGFMfMe/vEXtOnLZ78mxYx09uSDwncb3yh5v9RDdvCjFZfUMLCDtGLGIDREYcyHmXeLkn4+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
