travis:
  secure:
    BINSTAR_TOKEN: dxVwmhS59ulWVfXiD0FJLSdmJG4AzNHQQyrBBngkJ1SGubA6qHNrAPLuLQ2EZ18tx9T1FTcBc83/ld++J7ju6VM6U7HqUXcoFAKIwT9FfKhkNVNfZbF9ELBNoMdQuoGM7sJoJdCBc5BID/jf8xO9ldGq8PbuyXB+iINYV4RYyvisrOafFr5byBIcrD1asX87hYchmpxxPqF58Tq1elWUek88iJa9Q9vY09cfpft/ykoML7jVGofoSjVV1dQJ2k4WrKRdmD1omLGM69KMnqC2SlcDsNXw51I/y6NV8ic72kY77wfEC5YplTFGc1hzATWgUBkOBQdDl5UfXtjAomWBXNWF0nqHgi0g6EgGdnwlmFjnV8HhyHZOn1ODNHRM58us2WIqqL7Po0jBkjjyphaWTDhtfokZprHGNwQVQ5Gi2RUVH4hq/2a0/fAICj3/C8OEQ/I1U0lHINtkNIRTFABOAxxExcoaRZNEvKNM/IrULWW+dT59CIXL9urEv/rhoKSeOlob3JmKsv5ib2QY/HcRYHUpr4bgJJsj+Ktlk5NNND012214oYHBYGuvZRMAutA4ogmnIBuaZSWau08X77AAEDy4jfE15P6ijhemj98Y31/GtqXxbBn7eHN+qzm+3xxwujdDxPIwCjD5CWF+auEuJO9JbzcZfIBoVOqWFLPbh1s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
